export const camt053Rules = {
  messageType: 'camt.053.001',
  rootElement: 'BkToCstmrStmt',
  namespace: 'urn:iso:std:iso:20022:tech:xsd:camt.053.001.08',
  description: 'Bank to Customer Statement',
  mandatoryPaths: [
    'GrpHdr/MsgId',
    'GrpHdr/CreDtTm',
    'Stmt/Id',
    'Stmt/ElctrncSeqNb',
    'Stmt/CreDtTm',
    'Stmt/Acct/Id',
    'Stmt/Acct/Ccy',
    'Stmt/Bal/Tp/CdOrPrtry/Cd',
    'Stmt/Bal/Amt',
    'Stmt/Bal/CdtDbtInd',
    'Stmt/Bal/Dt/Dt',
  ],
  codeValues: {
    'Stmt/Bal/CdtDbtInd': ['CRDT', 'DBIT'],
    'Stmt/Bal/Tp/CdOrPrtry/Cd': [
      'OPBD', 'CLBD', 'CLAV', 'FWAV', 'INFO',
      'ITBD', 'ITAV', 'PRCD', 'XPCD',
    ],
  },
  formatRules: [
    { path: 'GrpHdr/MsgId', maxLength: 35 },
    { path: 'GrpHdr/CreDtTm', type: 'ISODateTime' },
    { path: 'Stmt/Bal/Amt', type: 'ActiveOrHistoricCurrencyAndAmount', attribute: 'Ccy' },
    { path: 'Stmt/Bal/Dt/Dt', type: 'ISODate' },
  ],
  extractionMap: {
    'Message ID': 'GrpHdr/MsgId',
    'Creation Date': 'GrpHdr/CreDtTm',
    'Statement ID': 'Stmt/Id',
    'Sequence Number': 'Stmt/ElctrncSeqNb',
    'Account ID': 'Stmt/Acct/Id/IBAN',
    'Account Currency': 'Stmt/Acct/Ccy',
    'Balance Type': 'Stmt/Bal/Tp/CdOrPrtry/Cd',
    'Balance Amount': 'Stmt/Bal/Amt',
    'Balance Currency': 'Stmt/Bal/Amt@Ccy',
    'Credit/Debit': 'Stmt/Bal/CdtDbtInd',
    'Balance Date': 'Stmt/Bal/Dt/Dt',
  },
};
