export const pacs008Rules = {
  messageType: 'pacs.008.001',
  rootElement: 'FIToFICstmrCdtTrf',
  namespace: 'urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08',
  description: 'FI to FI Customer Credit Transfer',
  mandatoryPaths: [
    'GrpHdr/MsgId',
    'GrpHdr/CreDtTm',
    'GrpHdr/NbOfTxs',
    'GrpHdr/SttlmInf/SttlmMtd',
    'CdtTrfTxInf/PmtId/EndToEndId',
    'CdtTrfTxInf/IntrBkSttlmAmt',
    'CdtTrfTxInf/ChrgBr',
    'CdtTrfTxInf/Dbtr/Nm',
    'CdtTrfTxInf/DbtrAcct/Id',
    'CdtTrfTxInf/DbtrAgt/FinInstnId',
    'CdtTrfTxInf/Cdtr/Nm',
    'CdtTrfTxInf/CdtrAcct/Id',
    'CdtTrfTxInf/CdtrAgt/FinInstnId',
  ],
  codeValues: {
    'GrpHdr/SttlmInf/SttlmMtd': ['CLRG', 'COVE', 'INDA', 'INGA'],
    'CdtTrfTxInf/ChrgBr': ['DEBT', 'CRED', 'SHAR', 'SLEV'],
  },
  formatRules: [
    { path: 'GrpHdr/MsgId', maxLength: 35 },
    { path: 'GrpHdr/CreDtTm', type: 'ISODateTime' },
    { path: 'GrpHdr/NbOfTxs', pattern: /^\d{1,15}$/ },
    { path: 'CdtTrfTxInf/IntrBkSttlmAmt', type: 'ActiveCurrencyAndAmount', attribute: 'Ccy' },
    { path: 'CdtTrfTxInf/PmtId/EndToEndId', maxLength: 35 },
  ],
  extractionMap: {
    'Message ID': 'GrpHdr/MsgId',
    'Creation Date': 'GrpHdr/CreDtTm',
    'Transactions': 'GrpHdr/NbOfTxs',
    'Settlement Method': 'GrpHdr/SttlmInf/SttlmMtd',
    'End-to-End ID': 'CdtTrfTxInf/PmtId/EndToEndId',
    'Amount': 'CdtTrfTxInf/IntrBkSttlmAmt',
    'Currency': 'CdtTrfTxInf/IntrBkSttlmAmt@Ccy',
    'Charge Bearer': 'CdtTrfTxInf/ChrgBr',
    'Debtor': 'CdtTrfTxInf/Dbtr/Nm',
    'Debtor IBAN': 'CdtTrfTxInf/DbtrAcct/Id/IBAN',
    'Debtor BIC': 'CdtTrfTxInf/DbtrAgt/FinInstnId/BICFI',
    'Creditor': 'CdtTrfTxInf/Cdtr/Nm',
    'Creditor IBAN': 'CdtTrfTxInf/CdtrAcct/Id/IBAN',
    'Creditor BIC': 'CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
  },
};
