export const pain001Rules = {
  messageType: 'pain.001.001',
  rootElement: 'CstmrCdtTrfInitn',
  namespace: 'urn:iso:std:iso:20022:tech:xsd:pain.001.001.09',
  description: 'Customer Credit Transfer Initiation',
  mandatoryPaths: [
    'GrpHdr/MsgId',
    'GrpHdr/CreDtTm',
    'GrpHdr/NbOfTxs',
    'GrpHdr/InitgPty/Nm',
    'PmtInf/PmtInfId',
    'PmtInf/PmtMtd',
    'PmtInf/NbOfTxs',
    'PmtInf/ReqdExctnDt/Dt',
    'PmtInf/Dbtr/Nm',
    'PmtInf/DbtrAcct/Id',
    'PmtInf/DbtrAgt/FinInstnId',
    'PmtInf/CdtTrfTxInf/PmtId/EndToEndId',
    'PmtInf/CdtTrfTxInf/Amt/InstdAmt',
    'PmtInf/CdtTrfTxInf/Cdtr/Nm',
    'PmtInf/CdtTrfTxInf/CdtrAcct/Id',
  ],
  codeValues: {
    'PmtInf/PmtMtd': ['CHK', 'TRF', 'TRA'],
    'PmtInf/CdtTrfTxInf/ChrgBr': ['DEBT', 'CRED', 'SHAR', 'SLEV'],
  },
  formatRules: [
    { path: 'GrpHdr/MsgId', maxLength: 35 },
    { path: 'GrpHdr/CreDtTm', type: 'ISODateTime' },
    { path: 'PmtInf/ReqdExctnDt/Dt', type: 'ISODate' },
    { path: 'PmtInf/CdtTrfTxInf/Amt/InstdAmt', type: 'ActiveCurrencyAndAmount', attribute: 'Ccy' },
    { path: 'PmtInf/CdtTrfTxInf/PmtId/EndToEndId', maxLength: 35 },
  ],
  extractionMap: {
    'Message ID': 'GrpHdr/MsgId',
    'Creation Date': 'GrpHdr/CreDtTm',
    'Transactions': 'GrpHdr/NbOfTxs',
    'Initiating Party': 'GrpHdr/InitgPty/Nm',
    'Payment Method': 'PmtInf/PmtMtd',
    'Execution Date': 'PmtInf/ReqdExctnDt/Dt',
    'Debtor': 'PmtInf/Dbtr/Nm',
    'Debtor IBAN': 'PmtInf/DbtrAcct/Id/IBAN',
    'End-to-End ID': 'PmtInf/CdtTrfTxInf/PmtId/EndToEndId',
    'Amount': 'PmtInf/CdtTrfTxInf/Amt/InstdAmt',
    'Currency': 'PmtInf/CdtTrfTxInf/Amt/InstdAmt@Ccy',
    'Creditor': 'PmtInf/CdtTrfTxInf/Cdtr/Nm',
    'Creditor IBAN': 'PmtInf/CdtTrfTxInf/CdtrAcct/Id/IBAN',
  },
};
